# Generated by Django 5.2.11 on 2026-02-05 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentication", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization (denormalized for performance). Use OrganizationUser for source of truth.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_branches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="organization",
            field=models.ForeignKey(
                help_text="Parent organization",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branches",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="branchuser",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_memberships",
                to="authentication.branch",
            ),
        ),
        migrations.AddField(
            model_name="branchuser",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_branch_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="branchuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branch_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="emailverificationtoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="organizationuser",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_org_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organizationuser",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_memberships",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="organizationuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="passwordresettoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this session belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["organization", "email"], name="authenticat_organiz_1fed11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["organization", "employee_id"],
                name="authenticat_organiz_9eaf5f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["organization", "is_active", "is_deleted"],
                name="authenticat_organiz_3f6976_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("organization", "email")},
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(
                fields=["organization", "is_active"], name="branches_organiz_8da68f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(
                fields=["name", "is_active"], name="branches_name_3c7ed7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="branch",
            unique_together={("organization", "name")},
        ),
        migrations.AddIndex(
            model_name="branchuser",
            index=models.Index(
                fields=["user", "is_active"], name="branch_user_user_id_467177_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="branchuser",
            index=models.Index(
                fields=["branch", "role", "is_active"],
                name="branch_user_branch__de6748_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="branchuser",
            unique_together={("user", "branch")},
        ),
        migrations.AddIndex(
            model_name="organizationuser",
            index=models.Index(
                fields=["user", "is_active"], name="organizatio_user_id_5200f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationuser",
            index=models.Index(
                fields=["organization", "role", "is_active"],
                name="organizatio_organiz_a637ab_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organizationuser",
            unique_together={("user", "organization")},
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["organization", "user", "is_active"],
                name="authenticat_organiz_139cd6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "is_active"], name="authenticat_user_id_f427c8_idx"
            ),
        ),
    ]
